/* eslint-disable react/no-unknown-property */
import React, { useCallback, useEffect, useState } from 'react';
import { Routes, Route, useLocation, useNavigate } from 'react-router-dom';
import {
  ActionIcon,
  Anchor,
  AppShell,
  Burger,
  Flex,
  Menu,
  Space,
  Title,
  useComputedColorScheme,
  useMantineColorScheme,
  useMantineTheme,
} from '@mantine/core';
import { useDispatch } from 'react-redux';
import {
  IconBrightness,
  IconDice5Filled,
  IconList,
  IconPlus,
  IconUpload,
  IconUserCircle,
} from '@tabler/icons-react';
import axios from 'axios';
import { useDisclosure } from '@mantine/hooks';

import { AppDispatch } from '../../store';
import { updatePath } from '../../features/App/slice';
// Start of app import code generated by oxgen. DO NOT EDIT.
// End of app import code generated by oxgen. DO NOT EDIT.


export const App = () => {
  const dispatch = useDispatch<AppDispatch>();
  const [opened, { toggle }] = useDisclosure();
  const location = useLocation();
  const navigate = useNavigate();
  const theme = useMantineTheme();

  const [uploadOpened, setUploadOpened] = useState<boolean>(false);

  const uploadModalOpened = useCallback(() => {
    setUploadOpened(true);
  }, []);

  const uploadModalClosed = useCallback(() => {
    setUploadOpened(false);
  }, []);

  const { toggleColorScheme } = useMantineColorScheme();
  const computedColorScheme = useComputedColorScheme('light', {
    getInitialValueInEffect: true,
  });

  useEffect(() => {
    dispatch(updatePath(location.pathname));
  }, [dispatch, location]);

  const navigateToRandomVideo = useCallback(() => {
    axios
      .get('/api/videos/random')
      .then(r => {
        const v = new Video(r.data);
        navigate(`/v/${v.id}`);
      })
      .catch(() => {});
  }, [navigate]);

  return (
    <div>
      <AppShell
        padding="md"
        header={{ height: 64 }}
        navbar={{
          width: 300,
          breakpoint: 'sm',
          collapsed: { mobile: !opened },
        }}
        styles={thisTheme => ({
          main: {
            backgroundColor:
              computedColorScheme === 'dark'
                ? thisTheme.colors.dark[8]
                : thisTheme.colors.gray[0],
          },
        })}
      >
        <AppShell.Header p="md">
          <div
            style={{ display: 'flex', alignItems: 'center', height: '100%' }}
          >
            <Flex
              align="center"
              direction="row"
              wrap="wrap"
              style={{ width: '100%' }}
            >
              <Burger
                opened={opened}
                onClick={toggle}
                hiddenFrom="sm"
                size="sm"
                color={theme.colors.gray[6]}
                mr="xl"
              />
              <Anchor
                c={computedColorScheme === 'dark' ? 'white' : 'dark'}
                href="/#/"
              >
                <Title order={3}>scenes</Title>
              </Anchor>

              <Space style={{ flex: 1 }} w="sm" />

              <Menu shadow="md" width={200}>
                <Menu.Target>
                  <ActionIcon
                    c={computedColorScheme === 'dark' ? 'white' : 'dark'}
                  >
                    <IconUserCircle strokeWidth={1} size={24} />
                  </ActionIcon>
                </Menu.Target>

                <Menu.Dropdown>
                  <Menu.Item
                    leftSection={<IconDice5Filled strokeWidth={1} size={14} />}
                    onClick={() => navigateToRandomVideo()}
                  >
                    Random video
                  </Menu.Item>
                  <Menu.Item
                    leftSection={<IconUpload strokeWidth={1} size={14} />}
                    onClick={uploadModalOpened}
                  >
                    Upload video
                  </Menu.Item>
                  <Menu.Item
                    leftSection={<IconPlus strokeWidth={1} size={14} />}
                    onClick={() => navigate('/ytsearch')}
                  >
                    Add new video
                  </Menu.Item>
                  <Menu.Item
                    leftSection={<IconList strokeWidth={1} size={14} />}
                    onClick={() => navigate('/untagged')}
                  >
                    Untagged videos
                  </Menu.Item>
                  <Menu.Item
                    leftSection={<IconBrightness strokeWidth={1} size={14} />}
                    onClick={() => toggleColorScheme()}
                  >
                    Toggle dark mode
                  </Menu.Item>
                </Menu.Dropdown>
              </Menu>
            </Flex>
          </div>
        </AppShell.Header>
        <AppShell.Navbar p="md" hidden={!opened} w={{ sm: 200, lg: 300 }}>
          <PathNavLinks toggleNav={toggle} />
        </AppShell.Navbar>
        <AppShell.Main>
          <Routes>
            <Route index element={<VideosList />} />
            {/* Start of app route code generated by oxgen. DO NOT EDIT. */}
            {/* End of app route code generated by oxgen. DO NOT EDIT. */}
          </Routes>
        </AppShell.Main>
      </AppShell>
      <UploadVideoModal opened={uploadOpened} onClose={uploadModalClosed} />
    </div>
  );
};
