import { configureStore } from '@reduxjs/toolkit';
import { reducer as app } from '../features/App/slice';
// Start of store import code generated by oxgen. DO NOT EDIT.
// End of store import code generated by oxgen. DO NOT EDIT.

export const store = configureStore({
  reducer: {
    app,
// Start of store reducer code generated by oxgen. DO NOT EDIT.
// End of store reducer code generated by oxgen. DO NOT EDIT.
  },
  middleware: getDefaultMiddleware =>
    getDefaultMiddleware()
// Start of store middleware code generated by oxgen. DO NOT EDIT.
// End of store middleware code generated by oxgen. DO NOT EDIT.
      .concat(movies.middleware)
      .concat(videos.middleware)
      .concat(tvShows.middleware)
      .concat(tropes.middleware)
      .concat(playlists.middleware)
      .concat(artists.middleware)
      .concat(channels.middleware)
      .concat(playlistItems.middleware),
});

// Infer the `RootState` and `AppDispatch` types from the store itself
export type RootState = ReturnType<typeof store.getState>;

// Inferred type: {posts: PostsState, comments: CommentsState, users: UsersState}
export type AppDispatch = typeof store.dispatch;
